[기업]회원가입 Controller 기능구현과 테스트코드 작성 (Feature/5)
f-lab-edu/conference-reservation pull request #43
Opened 2021-07-23 10:57 UTC by minkeun428

- 변경 사항
CorpController 회원가입 api 추가
CorpControllerTest 회원가입 테스트 추가

2021-07-24 01:42 UTC, f-kei commented
제목에 feature/5 를 쓰시도 좋지면
Pull Request 본문에 관련 이슈를 작성해주시는게 더 효율적입니다.

related issue : https://github.com/f-lab-edu/conference-reservation/issues/37

링크를 넣어주시면 자동으로 위와 같은 화면을 보실 수 있고

만약 intellij 에서 PulRequest 를 작성하신다면... 좀 더 편하게 이슈를 연결할수 있습니다.
https://shinsunyoung.tistory.com/41 등에서 해당 내용을 참고 하실 수 있어요!

2021-07-24 01:47 UTC, f-kei requested changes

2021-07-24 01:47 UTC, f-kei commented on src/test/java/com/reservation/conference/controller/CorpControllerTest.java
> +                .andExpect(status().isNotFound());
/corp/join/fail 라는 존재하지 않는 URI 로 로그인을 시도 했을때 실패를 확인 하는 테스트인가요?

'내가 만든적이 없으니 당연히  404' 가 나는 테스트를 하는 것 처럼 보이는데요. 
그렇다면 이 테스트는 삭제를 해도 문제가 없을 것 같습니다.

2021-07-24 13:37 UTC, minkeun428 commented on src/test/java/com/reservation/conference/controller/CorpControllerTest.java
> +                .andExpect(status().isNotFound());
네 삭제해도 될 것 같습니다!

2021-07-25 11:43 UTC, minkeun428 commented
리뷰 반영하여 Merge진행합니다. #37 #39

2021-07-25 11:44 UTC, merged